export const URLS = {
  GOOGLE_MAP_KEY: "AIzaSyDxwAM_9axxJTDHas08AsXEXHhjHJTP71U",
  BASE_URL2:"https://s4mmqthm52.ap-south-1.awsapprunner.com",
  // https://g3xhvfwyex.ap-south-1.awsapprunner.com
  BASE_URL: "https://htk3x7p5jf.ap-south-1.awsapprunner.com",
  IMAGE_URL: "https://readings-storage.s3.ap-south-1.amazonaws.com",
  GOOGLE_PACES_API_BASE_URL: "https://maps.googleapis.com/maps/api/place",
  REGISTER: "/api/auth/register",
  LOGIN: "/api/auth/login",
  FORGOT_PASSWORD_EMAIL: "/api/auth/forget-password",
  CHANGE_PASSWORD: "/api/auth/change-password",
  HOME: "/api/home",
  BOOK_DETAIL: "/api/books",
  BOOK_REQUEST: "/api/request-a-book",
  BOOK_SEARCH: "/api/search",
  GET_CARD_DISCOUNT:"/api/bins",
  // BOOK_SEARCH_By_CATEGORYID: "/api/search",

  BOOK_BY_CATEGORY: "/api/category/level1",
  BOOK_BY_SUB_CATEGORY: "/api/category/level1",
  BOOK_BY_CATEGORY_FOUR: "/api/category/level4",
  ADDRESSES: "/api/addresses",
  PROFILE: "/api/profile",
  DELETE_ACCOUNT: "/api/auth/delete-account",
  ADVANCE_SEARCH:"/api/searching-advance",
  High_DISCOUNT:"/api/high-discount-category/level1",
  WISHLIST:"/api/wishlist",
  BOOK_REVIEW:"/api/reviews",
  HIGH_DISCOUNT_CATEGORIES:"/api/categories/high-discounts",
  Add_CART_ITEM:"/api/cart/add-item",
  GET_ORDER_CART:"/api/cart/order-cart",
  UPDATE_CART_ITEM:"/api/cart/update-cart-item",
  DELETE_CART_ITEM:"/api/cart/delete-cart-item",
  PLACE_ORDER:"/api/cart/place-order",
  ORDER_CONFIRMATION:"/api/cart/order-confirmation",
 RECENT_ORDER_HISTORY:"/api/users/recent-history",
 INITIATE_CHECKOUT:"/api/cart/checkout/1",
 ORDER:"/api/orders",
 BUY_NOW:"/api/cart/buy-now",
 DAEWOO_ORDER:"https://careconnectapi.daewoo.net.pk:4432/api/Tracking/GetTrackingDetailsFastExByCN",
 POSTEX_ORDER:"https://api.postex.pk/services/courier/api/guest/get-order",

 SUB_MENU_BESTSELLER:"/api/sub-menu/international-bestsellers/I",
 SUB_MENU_COMING_SOON:"/api/sub-menu/coming-soon/C",
 SUB_MENU_NEW_PUBLICATON:"/api/sub-menu/new-in-our-publications/B",
 SUB_MENU_NEW_AT_READING:"/api/sub-menu/new-at-readings/E",
 SUB_MENU_NEW_RELEASE:"/api/sub-menu/new-releases/R",
 GUEST_TOKEN:"/api/auth/guest-user-token",
 CONVERT_PRICE:"/api/converted-price",
 CREATE_PAYMENT_INTENT:"/api/payments/intent/add-method",
 CAPTURE_AUTHORIZED_AMOUNT:"https://xstak-pay-stg.xstak.com/public/v1/payment/intent/confirm",
 REFUND_XPAYMENT:"/api/payments/refund-add-method-fee",
 GET_PAYMENT_METHOD:"/api/payments/payment-methods",
 DELETE_PAYMENT_METHOD:"/api/payments/method",
 PAY_WITH_CARD:"/api/payments/pay-using-token",
 CHECK_EMAIL_EXIST:"/api/payments/payment-methods",

};
